import * as vscode from "vscode";
import type { ExtensionSettings, ModelConfig } from "./types";
import { getRuntimeModelId } from "./config/settings";
import { Logger } from "./logger";

export async function resolveVisionProxyMessages(
	messages: readonly vscode.LanguageModelChatRequestMessage[],
	model: ModelConfig,
	settings: ExtensionSettings,
	logger: Logger,
	token: vscode.CancellationToken
): Promise<readonly vscode.LanguageModelChatRequestMessage[]> {
	if (!hasImages(messages)) {
		return messages;
	}

	const proxyModel = await selectVisionProxyModel(model, settings, logger);
	if (!proxyModel) {
		return replaceImagesWithText(messages, "[Image omitted: no vision proxy model is available.]");
	}

	const out: vscode.LanguageModelChatRequestMessage[] = [];
	for (const message of messages) {
		const imageParts: vscode.LanguageModelDataPart[] = [];
		const otherParts: vscode.LanguageModelInputPart[] = [];
		for (const part of message.content as readonly vscode.LanguageModelInputPart[]) {
			if (isImagePart(part)) {
				imageParts.push(part);
			} else {
				otherParts.push(part);
			}
		}
		if (imageParts.length === 0) {
			out.push(message);
			continue;
		}

		try {
			const prompt = settings.visionProxy.prompt;
			const visionMessage = vscode.LanguageModelChatMessage.User([
				...imageParts,
				new vscode.LanguageModelTextPart(prompt)
			]);
			const response = await proxyModel.sendRequest([visionMessage], {}, token);
			let description = "";
			for await (const chunk of response.stream) {
				if (chunk instanceof vscode.LanguageModelTextPart) {
					description += chunk.value;
				}
			}
			otherParts.push(new vscode.LanguageModelTextPart(formatVisionDescription(description)));
		} catch (error) {
			logger.warn("vision.proxy.failed", {
				model: model.id,
				error: error instanceof Error ? error.message : String(error)
			});
			otherParts.push(new vscode.LanguageModelTextPart("[Image omitted: vision proxy failed to describe it.]"));
		}

		out.push({
			role: message.role,
			content: otherParts
		} as unknown as vscode.LanguageModelChatRequestMessage);
	}
	return out;
}

async function selectVisionProxyModel(
	model: ModelConfig,
	settings: ExtensionSettings,
	logger: Logger
): Promise<vscode.LanguageModelChat | undefined> {
	const configured = model.visionProxyModelId;
	const shouldProxy = configured !== undefined
		? configured !== null && configured.trim().length > 0
		: settings.visionProxy.enabled && !model.vision;
	if (!shouldProxy) {
		return undefined;
	}

	const selfIds = new Set([model.id, getRuntimeModelId(model)]);
	const requestedId = configured?.trim() || settings.visionProxy.defaultModelId.trim();
	if (requestedId && !selfIds.has(requestedId)) {
		const selected = await vscode.lm.selectChatModels({ id: requestedId });
		const match = selected.find((candidate) => !selfIds.has(candidate.id));
		if (match) {
			return match;
		}
		logger.warn("vision.proxy.configuredModelUnavailable", { requestedId, model: model.id });
	}

	const allModels = await vscode.lm.selectChatModels();
	return allModels.find((candidate) => isUsableVisionModel(candidate, selfIds) && candidate.vendor !== "extendedModels")
		?? allModels.find((candidate) => !selfIds.has(candidate.id) && candidate.vendor !== "extendedModels")
		?? allModels.find((candidate) => !selfIds.has(candidate.id));
}

function isUsableVisionModel(model: vscode.LanguageModelChat, selfIds: Set<string>): boolean {
	const capabilities = (model as unknown as { capabilities?: { imageInput?: boolean } }).capabilities;
	return !selfIds.has(model.id) && Boolean(capabilities?.imageInput);
}

function hasImages(messages: readonly vscode.LanguageModelChatRequestMessage[]): boolean {
	return messages.some((message) => message.content.some((part) => isImagePart(part)));
}

function replaceImagesWithText(
	messages: readonly vscode.LanguageModelChatRequestMessage[],
	text: string
): vscode.LanguageModelChatRequestMessage[] {
	return messages.map((message) => {
		if (!message.content.some((part) => isImagePart(part))) {
			return message;
		}
		const content = (message.content as readonly vscode.LanguageModelInputPart[])
			.filter((part) => !isImagePart(part));
		return {
			role: message.role,
			content: [
				...content,
				new vscode.LanguageModelTextPart(text)
			]
		} as unknown as vscode.LanguageModelChatRequestMessage;
	});
}

function isImagePart(part: unknown): part is vscode.LanguageModelDataPart {
	return part instanceof vscode.LanguageModelDataPart && part.mimeType.startsWith("image/");
}

function formatVisionDescription(description: string): string {
	const trimmed = description.trim();
	return trimmed
		? `[Image description generated by Copilot Bro vision proxy]\n${trimmed}`
		: "[Image omitted: vision proxy returned an empty description.]";
}
